services:
  postgres:
    image: postgres:16
    container_name: nasa_climate_postgres
    environment:
      POSTGRES_DB: nasa_climate_project
      POSTGRES_USER: nasa_user
      POSTGRES_PASSWORD: nasa_password
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  metabase:
    image: metabase/metabase:latest
    container_name: nasa_climate_metabase
    ports:
      - "3000:3000"
    volumes:
      - metabase_data:/metabase-data
    environment:
      MB_DB_FILE: /metabase-data/metabase.db
    depends_on:
      - postgres

volumes:
  postgres_data:
  metabase_data:
